version: '2'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - './data/mysql:/var/lib/mysql'
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

