version: '2'
services:
#  mysql:
#    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
#    volumes:
#      - './data/mysql:/var/lib/mysql'
#    ports:
#      - 3307:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: root
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:latest
    ports:
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  kafka-manager:
    image: kafkamanager/kafka-manager
    environment:
      - ZK_HOSTS=zookeeper:2181
    ports:
    - 9000:9000

